---
services:
  torrent-ingest:
    build:
      context: ./server
      dockerfile: Dockerfile.local
    entrypoint: ./app --config /etc/config.yml
    volumes:
      - ./config.yml:/etc/config.yml:ro
      - ./data/transmission/downloads/complete:/data/downloads/complete
      - ./data/audiobooks:/data/audiobooks
      - ./data/music:/data/music
    ports:
      - 81:81
    environment:
      - TDLP_DEBUG=true
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - USER=test #optional
      - PASS=test #optional
    volumes:
      - ./data/transmission/config:/config
      - ./data/transmission/downloads:/downloads #optional
      - ./data/transmission/watch:/watch #optional
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

volumes:
  local-test:
